// Project:     Projet_I321, module ICT 321 "Programmer des systèmes distribués"
// Teacher:     Mr J. Ithurbide
// Authors:     Kilian Testard & Niels Delafontaine
// Description: API for a Pizza Foodtruck
// Date:        2025-12-18


// script to insert test data in the db, generated by AI

// config/TestDatas.js
const db = require('./database');

const seed = async () => {
    console.log("🚀 Début de l’insertion des données étendues...\n");

    // Fonction utilitaire pour exécuter du SQL avec une Promise
    const run = (sql, params = []) => new Promise((resolve, reject) => {
        db.run(sql, params, function (err) {
            if (err) reject(err);
            else resolve(this.lastID);
        });
    });

    try {
        // 1. NETTOYAGE
        await run("DELETE FROM pizza_ingredients");
        await run("DELETE FROM promotion");
        await run("DELETE FROM pizzas");
        await run("DELETE FROM ingredients");
        await run("DELETE FROM sqlite_sequence");

        // 2. INSERTION DES 10 INGRÉDIENTS
        const ingredientNames = [
            "Tomate", "Mozzarella", "Jambon", "Champignons", "Basilic",
            "Chèvre", "Miel", "Salami Piquant", "Olives", "Roquette"
        ];
        const ingredientIds = {};

        for (const name of ingredientNames) {
            const id = await run("INSERT INTO ingredients (name) VALUES (?)", [name]);
            ingredientIds[name] = id;
        }
        console.log("🍅 10 Ingrédients insérés !");

        // 3. DÉFINITION DES 5 PIZZAS
        const pizzas = [
            {
                name: "Margherita",
                description: "La classique : tomate, mozzarella et basilic frais.",
                imageUrl: "/images/margherita.jpg",
                price: 11.00,
                ingredients: ["Tomate", "Mozzarella", "Basilic"]
            },
            {
                name: "Reine",
                description: "Un indémodable aux champignons et jambon blanc.",
                imageUrl: "/images/reine.jpg",
                price: 13.50,
                ingredients: ["Tomate", "Mozzarella", "Jambon", "Champignons"]
            },
            {
                name: "Diavola",
                description: "Pour les amateurs de piquant avec son salami calabrais.",
                imageUrl: "/images/diavola.jpg",
                price: 14.50,
                ingredients: ["Tomate", "Mozzarella", "Salami Piquant", "Olives"]
            },
            {
                name: "Biquette",
                description: "Le mélange sucré-salé parfait chèvre et miel.",
                imageUrl: "/images/biquette.jpg",
                price: 15.00,
                ingredients: ["Mozzarella", "Chèvre", "Miel", "Roquette"]
            },
            {
                name: "Végétarienne",
                description: "Le jardin potager sur une pâte croustillante.",
                imageUrl: "/images/vegetarienne.jpg",
                price: 12.50,
                ingredients: ["Tomate", "Champignons", "Olives", "Roquette", "Basilic"]
            }
        ];

        for (const p of pizzas) {
            const pizzaId = await run(
                "INSERT INTO pizzas (name, description, imageUrl, price, created_at, updated_at) VALUES (?, ?, ?, ?, datetime('now'), datetime('now'))",
                [p.name, p.description, p.imageUrl, p.price]
            );

            // Insertion des liens pizza_ingredients
            for (const ingName of p.ingredients) {
                await run(
                    "INSERT INTO pizza_ingredients (pizza_id, ingredient_id) VALUES (?, ?)",
                    [pizzaId, ingredientIds[ingName]]
                );
            }
            p.id = pizzaId; // On stocke l'ID pour les promos plus tard
        }
        console.log("🍕 5 Pizzas et leurs liens ingrédients insérés !");

        // 4. INSERTION DES 3 PROMOTIONS
        // On récupère les IDs via le nom pour être sûr
        const getPizzaId = (name) => pizzas.find(p => p.name === name).id;

        const promos = [
            { pizza: "Margherita", pct: 10, start: "2024-01-01", end: "2025-12-31" },
            { pizza: "Diavola", pct: 25, start: "2024-06-01", end: "2024-12-31" },
            { pizza: "Biquette", pct: 15, start: "2024-01-01", end: "2026-01-01" }
        ];

        for (const promo of promos) {
            await run(
                "INSERT INTO promotion (pizza_id, percentage, starting_date, end_date) VALUES (?, ?, ?, ?)",
                [getPizzaId(promo.pizza), promo.pct, promo.start, promo.end]
            );
        }

        console.log("🔥 3 Promotions insérées !");
        console.log("\n✅ Base de données initialisée avec succès !");

    } catch (err) {
        console.error("❌ Erreur lors du seeding :", err);
    } finally {
        // Pas besoin de fermer la db ici si elle est gérée par le process
    }
};

// Exécution de la fonction
db.serialize(() => {
    seed();
});
