// script to insert test data in the db, generated by ChatGPT

const db = require('./database');

db.serialize(() => {
    console.log("🚀 Début de l’insertion de données...\n");

    // RESET DES DONNEES
    db.exec(`
        DELETE FROM pizza_ingredients;
        DELETE FROM promotion;
        DELETE FROM pizzas;
        DELETE FROM ingredients;
        DELETE FROM sqlite_sequence;  -- reset AUTOINCREMENT
    `);

    // --- INSERTION INGREDIENTS ---
    const ingredientsNames = [
        "Tomate",
        "Mozzarella",
        "Jambon",
        "Champignons",
        "Basilic"
    ];

    const ingredientIds = {}; // mapping: name → id

    const insertIngredient = db.prepare(`
        INSERT INTO ingredients (name) VALUES (?)`
    );

    ingredientsNames.forEach((name) => {
        insertIngredient.run(name, function () {
            ingredientIds[name] = this.lastID;
        });
    });

    insertIngredient.finalize(() => {
        console.log("🍅 Ingrédients insérés !");

        // --- INSERTION DES PIZZAS ---
        const pizzas = [
            {
                name: "Margherita",
                description: "Tomate, mozzarella, basilic",
                imageUrl: "/images/margherita.jpg",
                price: 12.50,
                ingredients: ["Tomate", "Mozzarella", "Basilic"]
            },
            {
                name: "Reine",
                description: "Tomate, mozzarella, jambon, champignons",
                imageUrl: "/images/reine.jpg",
                price: 14.90,
                ingredients: ["Tomate", "Mozzarella", "Jambon", "Champignons"]
            },
            {
                name: "Napolitaine",
                description: "Tomate, mozzarella, olives, anchois",
                imageUrl: "/images/napolitaine.jpg",
                price: 15.50,
                ingredients: ["Tomate", "Mozzarella"]
            }
        ];

        const insertPizza = db.prepare(`
            INSERT INTO pizzas (name, description, imageUrl, price)
            VALUES (?, ?, ?, ?)`
        );

        const pizzaIds = {}; // name → id

        pizzas.forEach((p) => {
            insertPizza.run(p.name, p.description, p.imageUrl, p.price, function () {
                pizzaIds[p.name] = this.lastID;
            });
        });

        insertPizza.finalize(() => {
            console.log("🍕 Pizzas insérées !");

            // --- LIENS pizza ↔ ingrédients ---
            const insertLink = db.prepare(`
                INSERT INTO pizza_ingredients (pizza_id, ingredient_id)
                VALUES (?, ?)`
            );

            pizzas.forEach((p) => {
                const pizzaId = pizzaIds[p.name];

                p.ingredients.forEach((ingName) => {
                    const ingId = ingredientIds[ingName];
                    insertLink.run(pizzaId, ingId);
                });
            });

            insertLink.finalize(() => {
                console.log("🔗 Associations pizza-ingredients insérées !");

                // --- PROMOTION ---
                const reineId = pizzaIds["Reine"];

                const insertPromo = db.prepare(`
                    INSERT INTO promotion (pizza_id, percentage, starting_date, end_date)
                    VALUES (?, ?, ?, ?)`
                );

                insertPromo.run(
                    reineId,
                    20,
                    "2024-01-01",
                    "2030-01-01"
                );

                insertPromo.finalize(() => {
                    console.log("🔥 Promotion insérée !");
                    console.log("\n✅ Données de test insérées avec succès !");
                });
            });
        });
    });
});
